name: Deploy to production

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/apps/projects/dapi
            export FRONTEND_IMAGE=ghcr.io/${{ github.repository }}-frontend:latest
            export BACKEND_IMAGE=ghcr.io/${{ github.repository }}-backend:latest
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml down || true
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker system prune -a -f