name: Scan

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan:
    name: Trivy scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner on frontend image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
          format: 'table'
          exit-code: 1
          # severity: 'CRITICAL,HIGH'
          severity: 'CRITICAL'
          ignore-unfixed: true

      - name: Run Trivy vulnerability scanner on backend image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
          format: 'table'
          exit-code: 1
          # severity: 'CRITICAL,HIGH'
          severity: 'CRITICAL'
          ignore-unfixed: true
